Update Release.yml

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -10,35 +10,41 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Checkout the code from the repository
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Set up Flutter (specify an exact version compatible with emotion_tracker)
       - name: Set up Flutter
         uses: subosito/flutter-action@v2
 
-      # Install dependencies
-      - name: Install dependencies
-        run: |
-          flutter pub get
+      - name: Cache Flutter Dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.pub-cache
+          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-flutter-
 
-      # Extract the release version from the branch name (e.g., refs/heads/v0.0.1 -> v0.0.1)
+      - name: Install dependencies
+        run: flutter pub get
+
       - name: Extract release version
         id: extract_version
         run: |
           VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
           echo "VERSION=${VERSION}" >> $GITHUB_ENV
 
-      # Print Current Directory
-      - name: Print Current Directory
-        run: |
-          echo "Current directory:"
-          pwd
-          echo "Listing contents of the current directory:"
-          ls -la
+      - name: Cache Linux Dependencies
+        uses: actions/cache@v3
+        with:
+          path: /var/cache/apt/archives
+          key: linux-dependencies
+          restore-keys: linux-dependencies
 
-      # --- Android release steps ---
+      - name: Install Linux Dependencies (Only if not cached)
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y libgtk-3-dev pkg-config
+
       - name: Generate Keystore (Android)
         run: |
           keytool -genkey -v -keystore $HOME/keystore.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias "$ANDROID_KEY_ALIAS" -dname "CN=Rohan Batra, OU=Open Source, O=Second Brain Database, L=Bidholi, ST=UK, C=IN" -storepass $ANDROID_KEYSTORE_PASSWORD -keypass $ANDROID_KEY_PASSWORD
@@ -47,47 +53,41 @@ jobs:
           ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
           ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
 
-      - name: Build APK for release (Android)
-        run: flutter build apk --release --no-shrink
-        env:
-            ANDROID_KEYSTORE: $HOME/keystore.jks
-            ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
-            ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
-            ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
-
-      - name: Build AAB for release (Android)
-        run: flutter build appbundle --release
-        env:
-            ANDROID_KEYSTORE: $HOME/keystore.jks
-            ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
-            ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
-            ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
-
-      # --- Linux release steps ---
-      - name: Install GTK+ 3.0 dependencies (Linux)
+      # --- Run Android, Linux, and Web Builds in Parallel ---
+      - name: Build Android and Linux in Parallel
         run: |
-          sudo apt-get update
-          sudo apt-get install -y libgtk-3-dev pkg-config
+          flutter build apk --release --no-shrink & 
+          flutter build appbundle --release & 
+          flutter build linux --release &
+          wait
 
-      - name: Build Linux version (Linux)
-        run: flutter build linux --release
+      - name: Cache AppImage Tool
+        uses: actions/cache@v3
+        with:
+          path: ./appimage/appimagetool-x86_64.AppImage
+          key: appimage-tool
+
+      - name: Ensure AppImage Tool Exists
+        run: |
+          if [ ! -f "./appimage/appimagetool-x86_64.AppImage" ]; then
+            wget -O ./appimage/appimagetool-x86_64.AppImage "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
+            chmod +x ./appimage/appimagetool-x86_64.AppImage
+          fi
+
+      - name: Build AppImage
+        run: ./appimage/appimagetool-x86_64.AppImage ./appimage/Emotion-Tracker.AppDir ./appimage/Emotion-Tracker.Appimage
 
       - name: Create tar.gz archive for Linux executable
         run: |
           mkdir -p release
-          tar -czvf "release/emotion_tracker-${{ env.VERSION }}.tar.gz" -C build/linux/x64/release/bundle emotion_tracker
-          ls -la release
+          tar -czvf "release/Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz" -C build/linux/x64/release bundle
 
-      # --- Web release steps ---
-      - name: Enable Web for Flutter (Web)
+      - name: Enable Web for Flutter (Web) and Build
         run: |
           flutter config --enable-web
-
-      - name: Build Flutter web app (Web)
-        run: |
           flutter build web --release
 
-      - name: GitHub Pages (Web)
+      - name: Deploy to GitHub Pages (Web)
         uses: crazy-max/ghaction-github-pages@v4.1.0
         with:
           build_dir: build/web
@@ -96,39 +96,59 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # --- Create or Update GitHub Release ---
+      - name: Verify Files Exist
+        run: |
+          echo "Verifying required files..."
+          FILES=(
+            "build/app/outputs/bundle/release/app-release.aab"
+            "build/app/outputs/flutter-apk/app-release.apk"
+            "appimage/Emotion-Tracker.Appimage"
+            "release/Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz"
+          )
+          for file in "${FILES[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "Error: $file does not exist!" >&2
+              exit 1
+            fi
+          done
+          echo "All files verified successfully."
+
       - name: Check if Release Exists
         id: check_release
         run: |
-          release_exists=$(gh release view $VERSION --json name --jq '.name' || echo "")
-          if [ -z "$release_exists" ]; then
-            echo "Release does not exist, creating a new one"
-            echo "create=true" >> $GITHUB_ENV
+          if gh release view $VERSION --json name --jq '.name' > /dev/null 2>&1; then
+            echo "release_exists=true" >> $GITHUB_ENV
           else
-            echo "Release exists, updating the existing release"
-            echo "create=false" >> $GITHUB_ENV
+            echo "release_exists=false" >> $GITHUB_ENV
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Create or Update GitHub Release
-        run: |
-          if [ "$CREATE" == "true" ]; then
-            echo "Creating new release"
-            gh release create $VERSION \
-              build/app/outputs/bundle/release/app-release.aab \
-              build/app/outputs/flutter-apk/app-release.apk \
-              release/emotion_tracker-${{ env.VERSION }}.tar.gz \
-              --title "Release $VERSION" \
-              --notes "Release $VERSION for branch $GITHUB_REF" \
-              --repo $GITHUB_REPOSITORY
-          else
-            echo "Updating existing release"
-            gh release edit $VERSION \
-              --title "Release $VERSION" \
-              --notes "Release $VERSION for branch $GITHUB_REF" \
-              --repo $GITHUB_REPOSITORY \
-              --assets "build/app/outputs/bundle/release/app-release.aab,build/app/outputs/flutter-apk/app-release.apk,release/emotion_tracker-${{ env.VERSION }}.tar.gz"
-          fi
+      - name: Delete Existing Release (if any)
+        if: env.release_exists == 'true'
+        run: gh release delete $VERSION --yes --repo $GITHUB_REPOSITORY
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create New Release
+        run: |
+          gh release create $VERSION \
+            release/Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz \
+            build/app/outputs/bundle/release/app-release.aab \
+            build/app/outputs/flutter-apk/app-release.apk \
+            appimage/Emotion-Tracker.Appimage \
+            --title "Release $VERSION" \
+            --notes "Release $VERSION for branch $GITHUB_REF" \
+            --repo $GITHUB_REPOSITORY
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Cleanup Temporary Files
+        run: |
+          echo "Cleaning up temporary files..."
+          rm -rf $HOME/keystore.jks
+          rm -rf build/
+          rm -rf release/
+          unset ANDROID_KEY_ALIAS
+          unset ANDROID_KEY_PASSWORD
+          unset ANDROID_KEYSTORE_PASSWORD
