Update Release.yml

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -10,28 +10,22 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Checkout the code from the repository
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # Set up Flutter (specify an exact version compatible with emotion_tracker)
       - name: Set up Flutter
         uses: subosito/flutter-action@v2
 
-      # Install dependencies
       - name: Install dependencies
-        run: |
-          flutter pub get
+        run: flutter pub get
 
-      # Extract the release version from the branch name (e.g., refs/heads/v0.0.1 -> v0.0.1)
       - name: Extract release version
         id: extract_version
         run: |
           VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
           echo "VERSION=${VERSION}" >> $GITHUB_ENV
 
-
-      # --- Android release steps ---
+      # --- Android Release ---
       - name: Generate Keystore (Android)
         run: |
           keytool -genkey -v -keystore $HOME/keystore.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias "$ANDROID_KEY_ALIAS" -dname "CN=Rohan Batra, OU=Open Source, O=Second Brain Database, L=Bidholi, ST=UK, C=IN" -storepass $ANDROID_KEYSTORE_PASSWORD -keypass $ANDROID_KEY_PASSWORD
@@ -42,21 +36,11 @@ jobs:
 
       - name: Build APK for release (Android)
         run: flutter build apk --release --no-shrink
-        env:
-            ANDROID_KEYSTORE: $HOME/keystore.jks
-            ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
-            ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
-            ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
 
       - name: Build AAB for release (Android)
         run: flutter build appbundle --release
-        env:
-            ANDROID_KEYSTORE: $HOME/keystore.jks
-            ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
-            ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
-            ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
 
-      # --- Linux release steps ---
+      # --- Linux Release ---
       - name: Install GTK+ 3.0 dependencies (Linux)
         run: |
           sudo apt-get update
@@ -72,24 +56,27 @@ jobs:
         run: cp -r build/linux/x64/release/bundle/* appimage/Emotion-Tracker.AppDir/
 
       - name: Run appimagetool
-        run: ./appimage/appimagetool-x86_64.AppImage ./appimage/Emotion-Tracker.AppDir ./appimage/Emotion-Tracker.Appimage
+        run: |
+          if ./appimage/appimagetool-x86_64.AppImage ./appimage/Emotion-Tracker.AppDir ./appimage/Emotion-Tracker.Appimage; then
+            echo "AppImage created successfully."
+          else
+            echo "Failed to create AppImage!" >&2
+            exit 1
+          fi
 
       - name: Create tar.gz archive for Linux executable
         run: |
           mkdir -p release
           tar -czvf "release/Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz" -C build/linux/x64/release bundle
-          ls -la release
 
-      # --- Web release steps ---
+      # --- Web Release ---
       - name: Enable Web for Flutter (Web)
-        run: |
-          flutter config --enable-web
+        run: flutter config --enable-web
 
       - name: Build Flutter web app (Web)
-        run: |
-          flutter build web --release
+        run: flutter build web --release
 
-      - name: GitHub Pages (Web)
+      - name: Deploy to GitHub Pages (Web)
         uses: crazy-max/ghaction-github-pages@v4.1.0
         with:
           build_dir: build/web
@@ -97,67 +84,67 @@ jobs:
           target_branch: gh-pages
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      
+
+      # --- File Verification Step ---
+      - name: Verify Files Exist
+        run: |
+          echo "Verifying required files..."
+          FILES=(
+            "build/app/outputs/bundle/release/app-release.aab"
+            "build/app/outputs/flutter-apk/app-release.apk"
+            "appimage/Emotion-Tracker.Appimage"
+            "release/Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz"
+          )
+          for file in "${FILES[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "Error: $file does not exist!" >&2
+              exit 1
+            fi
+          done
+          echo "All files verified successfully."
+
       # --- Create or Update GitHub Release ---
       - name: Check if Release Exists
         id: check_release
         run: |
-          release_exists=$(gh release view $VERSION --json name --jq '.name' || echo "")
-          if [ -z "$release_exists" ]; then
-            echo "Release does not exist, creating a new one"
-            echo "create=true" >> $GITHUB_ENV
+          if gh release view $VERSION --json name --jq '.name' > /dev/null 2>&1; then
+            echo "Release exists"
+            echo "release_exists=true" >> $GITHUB_ENV
           else
-            echo "Release exists, updating the existing release"
-            echo "create=false" >> $GITHUB_ENV
+            echo "Release does not exist"
+            echo "release_exists=false" >> $GITHUB_ENV
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      
-      - name: Verify Files Exist
-        id: verify_files
+
+      - name: Delete Existing Release (if any)
+        if: env.release_exists == 'true'
         run: |
-          if [ -f "build/app/outputs/bundle/release/app-release.aab" ] && \
-             [ -f "build/app/outputs/flutter-apk/app-release.apk" ] && \
-             [ -f "appimage/Emotion-Tracker.Appimage" ] && \
-             [ -f "Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz" ]; then
-            echo "All files exist"
-          else
-            echo "One or more files do not exist"
-            exit 1
-          fi
-      
-      - name: Create or Update GitHub Release
+          echo "Deleting existing release..."
+          gh release delete $VERSION --yes --repo $GITHUB_REPOSITORY
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create New Release
         run: |
-          echo "Checking if release exists..."
-          release_exists=$(gh release view $VERSION --json name --jq '.name' || echo "")
-          
-          if [ -n "$release_exists" ]; then
-            echo "Release exists, deleting the existing release..."
-            gh release delete $VERSION --yes --repo $GITHUB_REPOSITORY
-          else
-            echo "Release does not exist, creating a new release."
-          fi
-          
-          # Create the new release and upload the assets
-          echo "Creating a new release and uploading assets..."
+          echo "Creating new release..."
           gh release create $VERSION \
+            release/Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz \
             build/app/outputs/bundle/release/app-release.aab \
             build/app/outputs/flutter-apk/app-release.apk \
             appimage/Emotion-Tracker.Appimage \
-            Emotion-Tracker-Linux-x86-64-${{ env.VERSION }}.tar.gz \
             --title "Release $VERSION" \
             --notes "Release $VERSION for branch $GITHUB_REF" \
             --repo $GITHUB_REPOSITORY
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Cleanup Temporary Files and Environment Variables
+      - name: Cleanup Temporary Files
         run: |
-                echo "Cleaning up temporary files..."
-                rm -rf $HOME/keystore.jks  # Remove sensitive files like keystore
-                rm -rf build/              # Remove build artifacts
-                rm -rf release/            # Remove release artifacts
-                unset ANDROID_KEY_ALIAS    # Unset environment variables
-                unset ANDROID_KEY_PASSWORD
-                unset ANDROID_KEYSTORE_PASSWORD
-        
+          echo "Cleaning up temporary files..."
+          rm -rf $HOME/keystore.jks  # Remove sensitive files
+          rm -rf build/              # Remove build artifacts
+          rm -rf release/            # Remove release artifacts
+          unset ANDROID_KEY_ALIAS
+          unset ANDROID_KEY_PASSWORD
+          unset ANDROID_KEYSTORE_PASSWORD
